[build]
  base = "./client"

  publish = "./client/dist"

  command = "npm run build"

  [build.processing]
    skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200