[build]
  base    = "./client"
  publish = "./dist"
  command = "npm run build-only"
  [build.processing]
    skip_processing = true

[[headers]]
  for = "/assets/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200